baseURL = "http://yuchenblog.github.io/"
languageCode = "zh-Hans"
defaultContentLanguage = "zh"
title = "YuChenBolg"
theme = "hugo-theme-dream"

disablePathToLower = true

copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'

googleAnalytics = "UA-98295641-1"

disqusShortname = "g1eny0ung"

enableRobotsTXT = true

hasCJKLanguage = true

# https://gohugo.io/news/0.60.0-relnotes/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # background = "black"
  backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "YuChenzz"
  description = "~myBlog～"
  avatar = "/me/yy.jpg"
  motto = "hia~hia~hia"
  
  email = "g1enyy0ung@gmail.com"
  github = "g1eny0ung"
  linkedin = "钺杨g1eny0ung"
  codepen = "g1eny0ung"
  stackoverflow = "5676489/g1eny0ung"

  siteStartYear = 2016

  favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404Button = true
